Repository PlanoramaEvents/planorama, pull requests merged in 2024-06, with the labels that each got.

#1050 Plan 963 admin labels schedule page
  app/javascript/schedule/schedulable_sessions.vue
  app/javascript/schedule/schedule_session_search.vue
Labels: 3.6.0

#1051 remove the venues/rooms from sidebar for now
  app/javascript/navbar/side-navbar.vue
Labels: 3.6.0

#1052 Add status to reg sync
  app/controllers/registration_sync_data_controller.rb
  app/models/job_status.rb
  app/models/publication_status.rb
  app/models/registration_sync_status.rb
  app/policies/registration_sync_datum_policy.rb
  app/services/identity_service.rb
  app/workers/registration_sync_worker.rb
  config/routes.rb
  db/migrate/20240602172220_add_status_info_to_job.rb
  db/structure.sql
  lib/tasks/rbac.rake
Labels: 3.6.0

#1053 PLAN-994 Be consistent with timezone
  app/javascript/sessions/datetime_picker.vue
Labels: 3.6.0

#1060 PLAN-992 add attendance type to assigned sessions
  app/controllers/reports_controller.rb
  app/javascript/reports/reports_screen.vue
Labels: 3.6.0

#995 Plan 906 tags on publish
  app/controllers/publications_controller.rb
  app/serializers/conclar/session_serializer.rb
  app/services/publication_service.rb
  app/services/session_service.rb
  app/views/xml_templates/schedule.nokogiri
Labels: 3.6.0

#1058 Plan 983 snapshot and gate for conclar
  app/controllers/schedule_controller.rb
  app/workers/publication_worker.rb
Labels: 3.6.0

#1059 PLAN-991 Update session needs report for Tech/AV
  app/controllers/reports/session_reports_controller.rb
  app/javascript/reports/reports_screen.vue
  yarn.lock
Labels: 3.6.0

#1064 PLAN-785 Put the button back in the UI
  app/javascript/people/people_admin_tab.vue
Labels: 3.6.0

#1065 Plan 997 speed up session load
  app/controllers/sessions_controller.rb
  app/models/session.rb
  app/serializers/session_serializer.rb
Labels: 3.6.0

#1076 PLAN-1009 Remove code that causes dupe table in query
  app/services/session_service.rb
Labels: 3.6.1

#1081 PLAN-999 Update reg datum on person sync
  app/controllers/people_controller.rb
Labels: 3.6.2

#1082 PLAN-1006 Add any tag and label to sched search
  app/javascript/schedule/schedule_session_search.vue
Labels: 3.6.2

#1085 PLAN-1010 Speed up the query time for session retreival
  app/controllers/sessions_controller.rb
  app/serializers/session_serializer.rb
Labels: 3.6.2

#1086 PLAN-1000 Make the edit and trash for reg admin only
  app/javascript/people/people_admin_tab.vue
Labels: 3.6.2

#1088 PLAN-1011 Remove HTML elements in session descriptions
  app/views/xml_templates/schedule.nokogiri
Labels: 3.6.2

#1091 PLAN-1001 Bold name in confirmation dialog
  app/javascript/constants/strings.js
  app/javascript/people/people_admin_tab.vue
  app/javascript/people/person-edit-reg-number.vue
Labels: 3.6.2

#1092 PLAN-1000 disable unlink and link if not admin
  app/javascript/people/people_admin_tab.vue
Labels: 3.6.2

#1089 PLAN-1003 Add short title (max 40 chars) to session
  app/controllers/reports/program_ops_reports_controller.rb
  app/controllers/reports/session_reports_controller.rb
  app/controllers/sessions_controller.rb
  app/javascript/sessions/session.js
  app/javascript/sessions/session_sidebar.vue
  app/javascript/sessions/session_summary.vue
  app/models/person_schedule.rb
  app/models/published_session.rb
  app/models/session.rb
  app/serializers/person_schedule_serializer.rb
  app/serializers/published_session_serializer.rb
  app/serializers/session_serializer.rb
  db/migrate/20240622165823_add_short_title_to_sessions.rb
  db/structure.sql
  spec/models/session_spec.rb
Labels: 3.7.0

#1101 Plan-1012 Plan-1013 fixes to session list sched page
  app/javascript/schedule/schedulable_sessions.vue
Labels: 3.7.0

#1100 PLAN-1014 ensure that nested attribute changes mark model as dirty/changed for the 200/204 response
  app/controllers/concerns/resource_methods.rb
  app/models/application_role.rb
  app/models/concerns/dirty_associations.rb
  app/models/person.rb
  app/models/session.rb
  app/models/survey.rb
  app/models/survey/page.rb
  app/models/survey/question.rb
Labels: 3.7.0

#1063 PLAN-986 PLAN-985 PLAN-967 Add rce g24 integration
  app/controllers/integrations_controller.rb
  app/controllers/people_controller.rb
  app/controllers/rce_controller.rb
  app/javascript/configurations/config_editor.vue
  app/javascript/configurations/configurations_manager.vue
  app/javascript/configurations/single_config_manager.vue
  app/javascript/integrations/g24rce.mixin.js
  app/javascript/integrations/g24rce_settings.vue
  app/javascript/integrations/integration_settings.vue
  app/javascript/profile/person_schedule_display.vue
  app/javascript/profile/schedule_collapse.vue
  app/javascript/schedule/schedule_settings.vue
  app/javascript/store/integration.store.js
  app/lib/migration_helpers/plano_views.rb
  app/policies/integration_policy.rb
  app/policies/rce_policy.rb
  app/serializers/conclar/session_serializer.rb
  app/serializers/integration_serializer.rb
  app/serializers/person_schedule_serializer.rb
  app/services/session_service.rb
  config/routes.rb
  lib/tasks/g24.rake
  lib/tasks/parameters.rake
Labels: 3.7.0

#1113 Need event type and stage/room for room to
  app/controllers/rce_controller.rb
Labels: 3.7.0

#1111 Add UUID for sessions added
  app/controllers/reports/schedule_reports_controller.rb
Labels: 3.7.0

#1116 PLAN-1024 Add Hall 2 as an online stage
  lib/tasks/g24.rake
Labels: 3.7.0
